cookie:
  expiry_days: 30
  key: rag_normes_secret_key_change_me
  name: rag_normes_auth

credentials:
  usernames:
    LXS:
      email: lxs@example.com
      failed_login_attempts: 0
      first_name: LXS
      last_name: User
      logged_in: false
      password: HC
      roles:
        - admin
